### ISSUE TITLE
Preparation for Beta Announcement on Website

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-website#74]
We are approaching the beta release for the Torrust Project.  We are aiming for a consistent release of the Tracker and Index.

- [ ] Prepare Artwork for the Beta Release
- [ ] Draft visual design language and concept for beta-release on our website. (Beta release should somehow have their own style).
- [ ] Prepare a set of blog posts describing the beta process.
- [ ] Add Releases section to the Website.
- [ ] Start planing for the First Full-Release.

In particular it would be great if @matfantinel could come up with a visual beta-release concept for our website. :smiley:

**Comment by matfantinel** [comment]
@da2ce7 what do you mean by visual concept? Like maybe a banner or something in the home page?

**Comment by da2ce7** [comment]
I'm not a visual designer, however I suspect that we need to come up with some concept for the Torrust Website for releases and Announcements in general. A beta-release is some sort of combination of an announcement and a release.

@matfantinel If you have interest and spare working capacity, maybe you could provide some mock-up ideas for our team to consider?

**Comment by matfantinel** [comment]
@da2ce7 unfortunately I don't have much capacity in the short term to work on it. I'm not sure if this is what you have in mind, but usually what websites do is add a little banner/pill like the screenshot below to highlight new releases. Since it's the first release I guess it could be bigger than that example. Something like a card or `<Callout>` either right below the hero or right below the "What is Torrust" section. With copy and button like:

> ✨
> The Torrust Beta was released! 
> [View Announcement] (takes to the blog post)

![Arc 2023-09-03 at 14 28 09@2x](https://github.com/torrust/torrust-website/assets/24247035/9e19ccfb-4db6-4f75-82d2-1f35b4f639ee)

**Comment by cgbosse** [comment]
@da2ce7 
I think that this maybe also a good opportunity for our two new colleagues Graeme and Mario to have a look at it.
Graeme is looking into Svelte Kit right now and Mario offered himself for helping with design related things in a previous meeting where you were not able to attend.

**Comment by cgbosse** [comment]
Test Comment to see how the last-updated filter works.

**Comment by cgbosse** [comment]
Header for anouncement example.



![Image](https://github.com/torrust/torrust-website/assets/15330600/e456101a-36c5-4891-99ba-ea47121ed9ea)
